// THIS FILE IS AUTO-GENERATED BY FIGMA-CODEGEN
    // DO NOT EDIT IT MANUALLY
    
    import css from './ButtonSmall.module.css';
    
    // Props interface that affects css, generated from Figma
    export interface IButtonSmallStyleProps {
    
      value?: string;
  hi?: string;
    
    
    }
    
    export const useButtonSmallStyles = ({value, hi }: IButtonSmallStyleProps) => {
      const classes = [
        css.buttonsmall,
    
      ].join(' ');
    
      return {
        className: classes,
      };
    };
    