// THIS FILE IS AUTO-GENERATED BY FIGMA-CODEGEN
    // DO NOT EDIT IT MANUALLY
    
    import css from './Component.module.css';
    
    // Props interface that affects css, generated from Figma
    export interface IComponentStyleProps {
    
      hello?: string;
  title?: string;
    
    
    }
    
    export const useComponentStyles = ({ }: IComponentStyleProps) => {
      const classes = [
        css.component,
      ].join(' ');
    
      return {
        className: classes,
      };
    };
    