// THIS FILE IS AUTO-GENERATED BY FIGMA-CODEGEN
    // DO NOT EDIT IT MANUALLY
    
    import css from './InputCombo.module.css';
    
    // Props interface that affects css, generated from Figma
    export interface IInputComboStyleProps {
      size: 'default';
      subtext?: string;
    
    
    }
    
    export const useInputComboStyles = ({size }: IInputComboStyleProps) => {
      const classes = [
        css.inputcombo,
        css[`${size?.replace(/\s+/g, '-').toLowerCase()}`],
      ].join(' ');
    
      return {
        className: classes,
      };
    };
    